server:
  port: 8085

spring:
  application:
    name: ens-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"

      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path= /api/v1/auth/**, /api/v1/accounting/**, /api/v1/account/**, /api/v1/organizations/**

        - id: notification-service
          uri: http://localhost:8095
          predicates:
            - Path= /api/v1/notifications/**

        - id: recipient-service
          uri: http://localhost:8096
          predicates:
            - Path= /api/v1/recipient/**
